---

markets:
  exchange_one:
    sessions:
      tharpie_001:
        ip: 192.168.200.201
        port: 5000
        transport: tcp
      tharpie_002:
        ip: 192.168.201.201
        port: 5001
        transport: tcp
          
    cross_connects:
      xconn_tharp_abcd001:
        net_details:
          unicast:
            ipv4_subnets:
              0: { net: 192.168.200.0/24 }
              1: { net: 192.168.201.0/24 }
            advertised_ipv4_subnets:
              0: { net: 10.200.1.0/24 }
          bgp:
            peer_asn: 65001
            local_asn: 65002
            peer_ipv4: 10.100.0.1/30
            local_ipv4: 10.100.0.2/30
          port_type: routed
